name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions: {}

jobs:
  release:
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - name: Build
        run: swift build -c release --arch arm64 --product chronixd-capture
      - name: Compress
        run: tar -czf chronixd-capture-${GITHUB_REF_NAME}.tar.gz -C .build/apple/Products/Release chronixd-capture
      - name: Release
        run: gh release create ${GITHUB_REF_NAME} chronixd-capture-${GITHUB_REF_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
